### ISSUE TITLE
Infinite freeze on Sevtech: Ages

### ISSUE THREAD

**Issue by tst5000** [djpadbit/Sound-Physics#10]
When running Sevtech: Ages version 3.1.1, slightly modified with a few mods added, Minecraft will lock up and freeze indefinitely until the game is shut down (it does not do this when Sound Physics is not installed). The log only suggests that I disconnected from my singleplayer world's internal server, as far as I can tell, but here it is regardless: https://gist.github.com/tst5000/9b076f984b91a2c5b7419b2bd92addf2

And here is my mod list: https://gist.github.com/tst5000/127b5aec9d1f6682086384347c32aa51
plus Optifine HD U E3, Phosphor v.0.2.4 build46, littletiles 1.5.0 pre149, creativecore 1.9.54, and Vanillafix 1.0.10-99.

**Comment by djpadbit** [comment]
What is weird is that i don't see any logs from Sound Physics. Are you perhaps using a custom launcher ? Because iirc some custom launcher's log doesn't include stdout in it witch Sound Physics uses to log. If you are, could you upload the latest.log (or the relevant file) in the logs folder of your minecraft instance.

**Comment by tst5000** [comment]
I am using the Twitch launcher, which I believe doesn't modify the log, but here is the latest regardless. It's a different freeze, but it's the exact same issue (since i'm lazy and don't want to find the corresponding date/time for that specific freeze).
[2019-07-12-6.log](https://github.com/djpadbit/Sound-Physics/files/3387830/2019-07-12-6.log)

**Comment by djpadbit** [comment]
Does Sound Physics accually work while in-game ? because i still can't see its logs witch is very weird.

**Comment by tst5000** [comment]
Yes, it definitely does work. When I'm in my small storage shack, I can hear the chests' sounds echo slightly and all that other fancy stuff. There is a notable difference when the mod is installed versus when it is not.

**Comment by djpadbit** [comment]
Could you try this version [Sound-Physics-1.12.2.zip](https://github.com/djpadbit/Sound-Physics/files/3387884/Sound-Physics-1.12.2.zip), it should be using the logger and also have a bit more logging (I had to compressed the jar because github doesn't like jars) and post the log.

**Comment by tst5000** [comment]
I will be able to get back to you on that in about 4 hours. I'm going on a road trip right now, so I'm sorry for the unfortunate timing.

**Comment by djpadbit** [comment]
Ah i see, it's fine. I'll finish what i was working on in the meantime. I'll probably still be here in 4 hours though.

**Comment by tst5000** [comment]
Here is the log. Nothing seems out of the ordinary to me, but you would know better either way.
[latest.log](https://github.com/djpadbit/Sound-Physics/files/3389006/latest.log)

**Comment by djpadbit** [comment]
That is weird, there isn't the `[soundphysics]` prefix for logs but other than that it looks like a normal log with no errors. Do you have the dynamic environment evaluation enabled ?

**Comment by tst5000** [comment]
I don't have that enabled. Should I try it?

**Comment by djpadbit** [comment]
Nah, i don't really recommend it. It needs a rewrite. But that is very weird. Does it just hang on the dirt background while exiting the world ?

**Comment by tst5000** [comment]
No, it doesn't even change screens. It simply takes whatever frame it freezes on and hangs on to it, forever. The only reason I know that I disconnected from the internal server is because of the log.

**Comment by djpadbit** [comment]
That is extremely weird. And it doesn't happen without sound physics ? Have you tried other worlds ?

**Comment by tst5000** [comment]
It has not happened to me without it installed, even after much longer times in-world. I have not tried a different world with it, so I will try once I am home.

**Comment by djpadbit** [comment]
I'll close this issue. If needed I'll reopen it.
