### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by Gerek** [djpadbit/Sound-Physics#11]
Tried moving the folder into the mods folder but i went ingame and nothing has changed

**Comment by djpadbit** [comment]
You have to have forge installed first, then you have to download the latest release jar from the release tab (https://github.com/djpadbit/Sound-Physics/releases/latest) witch would be this file https://github.com/djpadbit/Sound-Physics/releases/download/1.0.7/Sound-Physics-1.12.2.jar and put it in the mods folder inside your minecraft directory.

**Comment by Gerek** [comment]
> You have to have forge installed first, then you have to download the latest release jar from the release tab (https://github.com/djpadbit/Sound-Physics/releases/latest) witch would be this file https://github.com/djpadbit/Sound-Physics/releases/download/1.0.7/Sound-Physics-1.12.2.jar and put it in the mods folder inside your minecraft directory.

Alright thank you. This makes caves much more enjoyable to explore and is much creepier.

**Comment by djpadbit** [comment]
Alright you seem to have made it work so i'm going to close the issue
