### ISSUE TITLE
Feedback: Dynamic Environment Evaluation is cool but still laggy

### ISSUE THREAD

**Issue by jivvy** [djpadbit/Sound-Physics#14]
I know you said it was implemented poorly, but it's _really_ cool and I hope it sees some love. Thanks :)

**Comment by djpadbit** [comment]
I too think it's cool, it's actually the reason i started this fork and the first thing i added. But yea the way i implemented it is not optimal and i have plans to rewrite it/ find a better way of doing what i want. Thanks for the feedback :)
