### ISSUE TITLE
How do you install the mod ?

### ISSUE THREAD

**Issue by vincentd3** [djpadbit/Sound-Physics#19]
how do i install this mod in minecraft forge ? i can never figure out how to get this mod to work.

**Comment by djpadbit** [comment]
Just like https://github.com/djpadbit/Sound-Physics/issues/11, you need to download the jar file from the release tab of the repository that you can find here https://github.com/djpadbit/Sound-Physics/releases and put it in the mods folder in your .minecraft directory.

**Comment by vincentd3** [comment]
oh ok. thanks.

**Comment by djpadbit** [comment]
It seems like you were able to install it, i'll close this issue then.
