### ISSUE TITLE
pull the 1.15.2 fork and update [Enhancement]

### ISSUE THREAD

**Issue by Tsoccerguy3** [djpadbit/Sound-Physics#23]
There is a 1.15.2 fork , can you check it out and update the master . thanks

**Comment by Tsoccerguy3** [comment]
https://github.com/AfterRebelion/Sound-Physics

**Comment by djpadbit** [comment]
I've been keeping an eye out for this fork for quite a while now but it's not finished yet, he ported most of the actual mod but not the coremod part yet so it's not fully functional. But when it will be, i'll probably merge it into master.

**Comment by Tsoccerguy3** [comment]
He has a working 1.15.2 . I have been testing for about 10 days

**Comment by beskhu3epnm** [comment]
> He has a working 1.15.2 . I have been testing for about 10 days

How do I go about installing and running this 1.15.2 mod? I assume [this](https://github.com/AfterRebelion/Sound-Physics/releases/tag/1.0.8) is the download link, but I'm not sure what to do with the source code.

**Comment by beskhu3epnm** [comment]
> First _working_ 1.15.2 release [Sound-Physics-1.0.8-1.15.2.jar.zip](https://github.com/djpadbit/Sound-Physics/files/4209572/Sound-Physics-1.0.8-1.15.2.jar.zip)
> 
> Lots of things missing, but fun to try anyway.
> Based on [secret secret](https://github.com/AfterRebelion/Sound-Physics/commit/8368120b6d898188c196f587686de622a8ac86f6)

**Comment by Tsoccerguy3** [comment]
You would need to clone his GIT and pull the forge branch , then compile it , for anyone interested . Alternately get the build above and test and report whats missing .
