### ISSUE TITLE
Log Errors whenever sound is played [1.12.2]

### ISSUE THREAD

**Issue by DarianLStephens** [djpadbit/Sound-Physics#27]
Whenever a sound plays, be that footsteps, lava pops, mob sounds, or menu clicks, this message will appear in the log:
[10:17:02] [Thread-7/ERROR] [minecraft/SoundManager]: Error in class 'SourceLWJGL OpenAL'
[10:17:02] [Thread-7/ERROR] [minecraft/SoundManager]: Invalid enumerated parameter value.

Everything ingame appears to be functional, but the sheer amount of things added to the log makes it difficult to look for actually important things, and makes the filesize much bigger than it needs to be.

**Comment by djpadbit** [comment]
I can't seem to be able to reproduce this but i've seen it happen before. Could you try [this](https://github.com/djpadbit/Sound-Physics/files/4534455/Sound-Physics-1.12.2.zip) version ? It should have more logging so i can see what is producing the errors.

**Comment by DarianLStephens** [comment]
This is the message I get now:
https://pastebin.com/w3V6hgES
Hopefully it can help somehow.

**Comment by djpadbit** [comment]
Mh it doesn't seem related to Sound Physics ? Do you have other mods installed ? Could you try [this](https://github.com/djpadbit/Sound-Physics/files/4535314/Sound-Physics-1.12.2.zip) version, it should have even more logging.

**Comment by DarianLStephens** [comment]
This is the error now, though it doesn't look like it's giving much more info, unfortunately:
https://pastebin.com/21HnN3Ax

I'm certain it's a conflict with another mod. If I disable Sound Physics, I never see that error, so it's something another mod is doing that is troublesome with Sound Physics in play.
I can try to figure out which one it is by going through each mod; maybe that will help as well.

**Comment by DarianLStephens** [comment]
Looks like it's an interaction between Sound Physics and [The Midnight](https://www.curseforge.com/minecraft/mc-mods/the-midnight).
I'm not sure what's going on, but I only get the error when that's enabled, and I also get the error with just The Midnight and Sound Physics enabled.

**Comment by djpadbit** [comment]
Could i get the complete log ?

**Comment by DarianLStephens** [comment]
Literally the whole thing, from loading the game to closing?

**Comment by djpadbit** [comment]
Just like from when you started the world to when you quit it

**Comment by DarianLStephens** [comment]
It happens on the main menu, too; the last few logs have just been me opening the game, clicking a button, and closing it.

**Comment by djpadbit** [comment]
Then just the whole log

**Comment by DarianLStephens** [comment]
MultiMC automatically uploaded this log: https://paste.ee/p/VaANW

**Comment by djpadbit** [comment]
I can't reproduce the error on my side, try [this](https://github.com/djpadbit/Sound-Physics/files/4536808/Sound-Physics-1.12.2.zip) version, it should have a bit more error checking in openal. I really don't know what is the problem though. I know that something makes an openal call without error checking and when the sound system checks for errors after changing the pitch it finds the old error that wasn't checked. At least that's what i think is happening.

**Comment by djpadbit** [comment]
[This](https://github.com/djpadbit/Sound-Physics/files/4536962/Sound-Physics-1.12.2.zip) version should have the fix and shouldn't error out anymore. I added a patch that removes the Midnight's reverb stuff because it was redundant with Sound Physics's functionality and was causing some errors.

**Comment by DarianLStephens** [comment]
Does that mean The Midnight adds reverb? Is that global throughout the dimension, or just underground?
If it's through the whole dimension, I'm not certain Sound Physics alone will do the same job.
Could Sound Physics be made to replicate that, though?

**Comment by djpadbit** [comment]
The Midnight adds reverb to the whole dimension, but i'd be pretty tedious to add back the exact feature that it added into Sound Physics which is why i opted not to do it. If you still want the reverb, you can disable the patch in the Sound Physics's mod config, but the errors will come back.

**Comment by DarianLStephens** [comment]
Would it be possible to just make everything be super-reverb-y? That would at least simulate it.
The dimension does lose a little something when there's no echo.

**Comment by djpadbit** [comment]
I understand what you mean but the problem is that there is a 4 effect limit on openal soft and the 4 are already being used for the different reverbs of Sound Physics. So i can't just add another reverb just for The Midnight dimension otherwise this wouldn't have been a problem in the first place. It would require quite a bit more work to make something similar and it wouldn't even sound the same.

**Comment by DarianLStephens** [comment]
Oh, I don't mean an entirely new effect, I mean trick the sound system in to thinking everything's got massive reverb while in the dimension, so Sound Physics does its thing with that.
It wouldn't be the same, but it would be similar.

**Comment by djpadbit** [comment]
I could modify the send gains for the reverb effects to not have a minimum of 0 so that there it would always have a bit of reverb but it would kind of break Sound Physics. I won't push it to master but [here](https://github.com/djpadbit/Sound-Physics/files/4540125/Sound-Physics-1.12.2.zip)'s a version that has always some reverb in the midnight dimension.

**Comment by DarianLStephens** [comment]
I'm not entirely sure what you mean about it breaking Sound Physics, because it seems to work roughly how The Midnight intends.
It might not allow for proper Sound Physics-y effects, but it does restore The Midnight's own ambiance.
If feasible, maybe it could be an off-by-default option for further Midnight compatibility, with the caveat that it's at the cost of the full Sound Physics experience in the dimension?
