### ISSUE TITLE
Portal sound from entering the End sounds very distant?

### ISSUE THREAD

**Issue by floral-qua-floral** [djpadbit/Sound-Physics#29]
When entering the End via an End Portal, the travel.ogg sound effect can be heard, but it sounds really quiet - like it's either behind something or rather far away. The sound can be heard correctly when entering the End in vanilla 1.12, or on the wiki [here](https://minecraft.gamepedia.com/Nether_portal#Sounds) (although it's pitched down a little in-game).

**Comment by djpadbit** [comment]
This was due to the sound being converted to mono. This should be fixed in the next release, [here](https://github.com/djpadbit/Sound-Physics/files/4622398/Sound-Physics-1.12.2-1.0.8-1.zip) is a preview build in the meantime.
