### ISSUE TITLE
[Bug] Sounds in some conditions appear muffled even if they shouldn't.

### ISSUE THREAD

**Issue by Lgmrszd** [djpadbit/Sound-Physics#30]
I've encountered this several times in different situations, however for now I have clear instructions of reproducing only one of it. I'll add more there if come up with instructions, although I believe they have common cause.
Muffled door sound:
1. Place wooden door
2. Stand next to it (from the "inside", in the blockspace occupied by door)
3. Opening it will result with uncomfortably quiet sound.
This effect is even more noticeable when door is in actual door frame (two blocks on each side)

**Comment by djpadbit** [comment]
It should be fixed, [here](https://github.com/djpadbit/Sound-Physics/files/4706807/Sound-Physics-1.12.2-1.0.8-1.zip)'s a build with the changes
