### ISSUE TITLE
Cubic chunks audio cuts out.

### ISSUE THREAD

**Issue by deadspidervenom** [djpadbit/Sound-Physics#31]
So when playing it seems to work fine till you go bellow 0 then all audio effect half cut out, what i mean is like you can hear creatures like there right next to you, but thats it, no other audio effects from sound physics.

**Comment by djpadbit** [comment]
Yes, it makes sense because sound physics doesn't process sounds that are at y <= 0 because in the normal game, nothing is supposed to be there and that's also how it determines if a sound is in-game or in the menus. I'm currently not at home but when i come back i'll try to make a fix.

**Comment by djpadbit** [comment]
I'm sorry i procrastinated a bit on this issue because i found some more issues while dealing with this one, but It should be fixed now, [here](https://github.com/djpadbit/Sound-Physics/files/4840935/Sound-Physics-1.12.2-1.0.9.zip)'s a build with the changes.
