### ISSUE TITLE
Ticking Entity Crash on 1.12.2

### ISSUE THREAD

**Issue by n8atnite** [djpadbit/Sound-Physics#33]
Latest version of 1.12.2 Forge.
Latest version of Sound Physics.
Latest version of Dynamic Surroundings.

I have not tested whether this crash occurs without DS present in the modslist.

[crash-2020-06-21_23.50.40-server.txt](https://github.com/djpadbit/Sound-Physics/files/4812039/crash-2020-06-21_23.50.40-server.txt)
[crash-2020-06-22_00.00.49-server.txt](https://github.com/djpadbit/Sound-Physics/files/4812040/crash-2020-06-22_00.00.49-server.txt)
[crash-2020-06-22_00.03.32-server.txt](https://github.com/djpadbit/Sound-Physics/files/4812041/crash-2020-06-22_00.03.32-server.txt)

**also note that these crashes occur during world generation. It is impossible to run or even generate a world with this mod configuration.

**Comment by djpadbit** [comment]
I don't think you're running the latest Sound Physics version. The latest version is available on the [releases](https://github.com/djpadbit/Sound-Physics/releases)  page. [Here](https://github.com/djpadbit/Sound-Physics/releases/download/1.0.9/Sound-Physics-1.12.2-1.0.9.jar)'s a direct link to the latest version. It should work fine with this one.
