### ISSUE TITLE
Suggestion: Add echoes inside of caves

### ISSUE THREAD

**Issue by H4kt** [djpadbit/Sound-Physics#34]
Just stumbled across this mod.
My ears.. they really loved that..
By the way, while testing it, I assumed something was missing and then I figured it out.. **echoes**..

All in all thaks a lot for keeping this project alive. Never ever seen something better than this!

**Comment by djpadbit** [comment]
It would be nice indeed and openal EFX does support echo effects but sadly the openal-soft version shipped with minecraft 1.12.2 only has support for up to 4 aux effect sends per source, all of them already being used for the reverbs. In 1.13 and over, minecraft uses lwjgl 3 which uses a newer openal-soft version that supports up to 16 aux effect sends so it could be doable.

**Comment by djpadbit** [comment]
Actually after a bit more of looking around, it seems like there is echo built-in to the eax reverb so i can maybe do something.

**Comment by H4kt** [comment]
I'll try it later
Thanks!

**Comment by andris86** [comment]
My suggestion is: don’t make echo and reverb a seperate thing. A theory is simple: when a sound is made, it bounces off the nearest surfaces. In an area where objects are close to the sound source (room, hallway, narrow street), sound waves bounce off the objects multiple times. We call it reverb. But in a situation when nearest objects are not so close to a sound source (tall buildings, mountains, a gigantic cave) sound waves can bounce off only a few times. That’s an echo. That means that reverb and echo can’t both be active in a same location occurring from the same sound source simultaneously. I hope you got the idea. Thanks for reading!

**Comment by H4kt** [comment]
I've just found some time to test it
And this is beautiful, thanks a lot!
