### ISSUE TITLE
1.16 version?

### ISSUE THREAD

**Issue by l0m-dev** [djpadbit/Sound-Physics#35]
Could you update it to the newest minecraft version? The nether update is really good.

**Comment by djpadbit** [comment]
I'll look into when forge for 1.16 goes stable. Since i already did most of the hard work porting it to 1.15.2, it shouldn't be that hard to go to 1.16.

**Comment by Immortalizd** [comment]
:eyes:

**Comment by Oaklizard-2047** [comment]
how about fabric? will you port it to fabric?

**Comment by djpadbit** [comment]
I won't switch to fabric because it would require a bit too much work and coremods are less supported in fabric (at least as far as i'm aware). Also i already did most of the heavy work to port it to newer versions under forge, porting from 1.15.2 to 1.16 should be a lot easier than 1.12.2 to 1.15.2.

**Comment by Nixel1324** [comment]
Forge 1.16.3 went stable, can't wait to see this mod working again!

**Comment by Gann4** [comment]
Waiting for 1.16.3 version!
Any way to get notified in an easier way about an update for this project/mod?

**Comment by djpadbit** [comment]
I updated the 1.15.2 version to be on the latest release, i'll look into porting it to 1.16.3 in the near future (this week maybe).
There isn't really any better way of getting updates for this mod yet, i'm still looking into making a curseforge page but when i make one probably there.

**Comment by djpadbit** [comment]
I've finished porting it to 1.16.3 but i haven't tested it fully. The download link is in the latest release alongside the 1.15.2 version [here](https://github.com/djpadbit/Sound-Physics/releases). It was very easy to port from 1.15.2, i pretty much had to do nothing compared to porting from 1.12.2 to 1.15.2. So it should be updated alongside the 1.15.2 port without much hassle. I'll close the issue but feel free to open issues if you find any bugs with the 1.16 or 1.15 versions.
