### ISSUE TITLE
[Suggestion] almost all the sounds from other mods will work?

### ISSUE THREAD

**Issue by gatoborrachon** [djpadbit/Sound-Physics#39]
i mean, mods like HBM's, the future port of Traincraft, Railcraft, etc.

**Comment by djpadbit** [comment]
I'm not home currently so i can't test for sure but as long as the mod uses the standard minecraft sound engine there shouldn't be too much problems. Although Sound Physics doesn't currently handle moving sounds so minecarts and trains won't get effects. The only problems that could arise is if it falsely detects the sounds as one it shouldn't process or as a block sound if it isn't.

**Comment by djpadbit** [comment]
I've tried HBM and Railcraft and they seem to work fine.

**Comment by gatoborrachon** [comment]
totally my bad, idk why i forget things, i really should tested this by myself but many thanks for doing it
