### ISSUE TITLE
Weird note block voice issue

### ISSUE THREAD

**Issue by GamingMidi** [djpadbit/Sound-Physics#43]
I've been fiddling around with the SoundPhysics config for a while now, and no matter what I do I cannot find a fix for this one note block issue, where any note will cut off any other existing sounds, including other notes, so only 1 note can be played at one time.
Can you please fix this? It makes note block songs sound like absolute crap.

**Comment by djpadbit** [comment]
I can't seem to be able to reproduce the issue, could you give more details about your setup ? Like if you have other mods and how you can easily reproduce the issue.

**Comment by GamingMidi** [comment]
Its extremely easy to reproduce here, and I do have other mods, I'm running SoundPhysics in my modpack (Aldim) if that helps you, to reproduce it just try spamming a note block, or make a short polyphonic note block song and you'll quickly hear it.

**Comment by GamingMidi** [comment]
Here's an example of the issue: https://cdn.discordapp.com/attachments/690300592165486641/757874381195182080/noteblock_cutoff_problem.mp3

**Comment by djpadbit** [comment]
I tried the modpack without Sound Physics and it seems to still do it, so i don't think it's the issue.

**Comment by GamingMidi** [comment]
Huh... before 1.0.5 this issue wasn't happening (1.0.5 is when I replaced SoundFilters with SoundPhysics)... Any suggestions how I could trace the issue then? If you don't mind.

**Comment by djpadbit** [comment]
It's a really weird bug, i don't really know. Maybe look at the changes between the 2 versions and see what mods got changed to narrow it down. I looked through the mod list but none of them really look suspicious.

**Comment by GamingMidi** [comment]
Still very confused to this day of what the issue is. I narrowed down a mods list as to what changed between them
SoundFIlters -> SoundPhysics
+ weeping-angels-46
+ LegendOfHerobrine-1.12.2-0.5.2
+ cc-tweaked-1.12.2-1.89.2
+ OpenComputers-MC1.12.2-1.7.5.192
+ EyesInTheDarkness-0.0.5

I am going to try 1.0.4 again to double check that the bug isn't there. I'll comment again if I can't figure it out still, in that case do you know what else I could try?

**Comment by GamingMidi** [comment]
I finally found it. It was the Good Nights Sleep mod. Idk why.
