### ISSUE TITLE
[Suggestion] Gliby's Voice Chat support?

### ISSUE THREAD

**Issue by Cosmiiko** [djpadbit/Sound-Physics#46]
Hi! First of all thanks for the fork, works great on my server!
I was wondering if it would be possible to make this work with [Gliby's Voice Chat Reloaded](https://www.curseforge.com/minecraft/mc-mods/glibys-voice-chat-reloaded) ([github](https://github.com/Icosider/GlibysVoiceChat))?
Could you imagine you and your friends' voices having reverb in caves? Would be so great.

However on my side of things, having the Voice Chat mod installed seems to prevent this mod from working altogether... No reverb anywhere anymore...
The reverb does work (on blocks, not voices) with [another fork of the voice mod](https://www.curseforge.com/minecraft/mc-mods/immersive-voice) but the source code isn't available anymore...

**Comment by djpadbit** [comment]
The voice doesn't get affected by Sound Physics but i've fixed the no Sound Physics at all problem. [Here](https://github.com/djpadbit/Sound-Physics/files/5506958/Sound-Physics-1.12.2-1.0.10-1.zip)'s a build with the fix. I'm looking into making the voices affected.

**Comment by Cosmiiko** [comment]
Wow, thank you so much for the quick answer and work!

**Comment by djpadbit** [comment]
I added support for Sound Physics to Gliby's VC now. [Here](https://github.com/djpadbit/Sound-Physics/files/5512898/Sound-Physics-1.12.2-1.0.10-1.zip)'s a build with the new changes. (I also fixed the spelling because i wrote Gibly rather than Gliby)
