### ISSUE TITLE
IC2 Classic Compatibility

### ISSUE THREAD

**Issue by DarianLStephens** [djpadbit/Sound-Physics#47]
You apparently recently added compatibility with IC2, but it doesn't seem to apply to IC2 Classic.
The machines make no sound, and the console is absolutely flooded with errors relating to the sound system:
https://pastebin.com/NGhBmbxu

**Comment by djpadbit** [comment]
It was for IC2 Exp. I'm gonna be honest, i forgot about IC2 Classic. I'll look into the issue.

**Comment by djpadbit** [comment]
I've fixed it, [Here](https://github.com/djpadbit/Sound-Physics/files/5578385/Sound-Physics-1.12.2-1.0.10-1.zip)'s a build with the changes.
