### ISSUE TITLE
1.8.9 version

### ISSUE THREAD

**Issue by Blackrucat** [djpadbit/Sound-Physics#49]
Since I was a child playing this game I've been always looking for a 1.8.9 version of this mod.

**Comment by djpadbit** [comment]
I've already ported it to 1.8.9 in the past, see https://github.com/djpadbit/Sound-Physics/issues/9. It's not a very up to date version and i won't update it but at least it's there.

**Comment by Blackrucat** [comment]
This is the fastest answer I ever had here in Github, thank you guys!
