### ISSUE TITLE
No config file?

### ISSUE THREAD

**Issue by Kutaren-Kraterboy** [djpadbit/Sound-Physics#51]
Im not sure if im just being stupid or what but there is no config option after installing the mod with forge. 
![noconfig](https://user-images.githubusercontent.com/73782093/101596314-da124080-39c2-11eb-9eef-8caade08c5b9.PNG)

**Comment by DarianLStephens** [comment]
I could be wrong or have outdated information, but I'm pretty sure forge hasn't reimplemented in-game configuration yet, so you must edit the file manually.
It's in your 'config' folder, if you can believe it.

**Comment by djpadbit** [comment]
Yes as @DarianLStephens said, forge didn't re implement the config gui like in 1.12.2, you can do it but it's very annoying to do. At least as far as i'm aware.

**Comment by VirtualGaming1** [comment]
just going though and this should help

mod called configured
https://www.curseforge.com/minecraft/mc-mods/configured
