### ISSUE TITLE
I need help adding in the sound physics

### ISSUE THREAD

**Issue by fairdyrus** [djpadbit/Sound-Physics#53]
ok look I have been playing this game for like a week and I don't know anything about this, but can you help me add in the sound physics, all I need is for you to type instructions in the comments plz

**Comment by djpadbit** [comment]
You need to install Minecraft forge for the version you want to use it in, the downloads are [here](https://files.minecraftforge.net/). There's Sound Physics for Minecraft 1.12.2,1.15.2 and 1.16.3-1.16.4 so download the required forge version. Then you have to go in your .minecraft (do %appdata%/.minecraft in the explorer bar) and put the Sound Physics jar (which you can download on the latest release page [here](https://github.com/djpadbit/Sound-Physics/releases/latest)) in the mods folder.

**Comment by fairdyrus** [comment]
So does it just integrate the mod automatically or do I have to do a 10 hour process

**Comment by djpadbit** [comment]
No after installing forge and putting the mod in the mods folder you launch minecraft and it works fine.

**Comment by fairdyrus** [comment]
ok but I just went in a cave and there is no reverb

**Comment by djpadbit** [comment]
Did you launch the game with the forge profile ? Do you see Forge in the F3 debug info ?

**Comment by fairdyrus** [comment]
oh thx! I was only running it in optifine I'll see if it works

**Comment by djpadbit** [comment]
You can put the optifine jar in the mods folder aswell to get it with forge

**Comment by fairdyrus** [comment]
ok so I hear a spider on the other side of a wall way quieter is that how it's supposed to work?

**Comment by djpadbit** [comment]
Yes the sound is getting attenuated, if you go in a cave you should get some reverb.

**Comment by fairdyrus** [comment]
with what kind of mobs/items/breaking blocks

**Comment by djpadbit** [comment]
What do you mean ?

**Comment by fairdyrus** [comment]
what kind of blocks can make echos/reverbs

**Comment by fairdyrus** [comment]
and also can you make a 1.16.4 version of this?

**Comment by djpadbit** [comment]
All of them, it's based on the environment around you and the sound. But some blocks reflect sound more than others, stone for example reflects more than wood or dirt. The 1.16.3 version is compatible with 1.16.4.

**Comment by fairdyrus** [comment]
does it depend on how big the cave is too

**Comment by djpadbit** [comment]
Yes

**Comment by fairdyrus** [comment]
ok thank you that's all I need

**Comment by djpadbit** [comment]
Alright i'm going to close the issue then.
