### ISSUE TITLE
Update to 1.16.4, and upload to CurseForge.

### ISSUE THREAD

**Issue by MagmaSlime123** [djpadbit/Sound-Physics#55]
Title says all. It'd be nice if this was on CurseForge, as it'd allow for the use of this mod in modpacks.

**Comment by djpadbit** [comment]
The 1.16.3 version of the mod should work fine in 1.16.4 as far as I tested it. And for CurseForge, it's already been said in #40.

**Comment by MagmaSlime123** [comment]
Oh.
