### ISSUE TITLE
This mod + SnowRealMagic = Crash.

### ISSUE THREAD

**Issue by MagmaSlime123** [djpadbit/Sound-Physics#56]
[crash-2021-01-08_11.49.57-client.txt](https://github.com/djpadbit/Sound-Physics/files/5789124/crash-2021-01-08_11.49.57-client.txt)

![image](https://user-images.githubusercontent.com/51277766/104058320-64a7b480-51a8-11eb-98f8-9aadea6c7bbb.png)

**Comment by djpadbit** [comment]
I'm aware of the compatibility issues with other mods in 1.16, I need to look into it.

**Comment by MagmaSlime123** [comment]
Ah. Mk. Sorry.
