### ISSUE TITLE
Not working at all in 1.16.3

### ISSUE THREAD

**Issue by sparton76** [djpadbit/Sound-Physics#58]
Tried it, doesn't work. The only other thing in my mods folder is optifine, and I'm not using any shaders or anything. I've replicated my friends conditions, it works perfectly for him. Forge 34.1.0, newest version of this mod. The mod shows up in my mods page on the main menu, but when in-game it simply doesn't change anything.

**Comment by sparton76** [comment]
I'm closing this now. I think I figured it out. Though its effects like reverb footsteps in caves are borderline unnoticeable compared to the 1.12 version, I got it to work by completely deleting and freshly reinstalling Minecraft and Forge.

**Comment by djpadbit** [comment]
Yeah I'm not really a fan of how it turned out in the newer versions, the values are the same between 1.12.2 and 1.13+ but the openal-soft version changed with the switch to lwjgl 3.0 and the reverb changed so I can't really do much apart from trying to tune the values to make it more noticeable.
