### ISSUE TITLE
[BUG] Latest commit conflict with Liteloader 1.12.2 result is no sound

### ISSUE THREAD

**Issue by Tsoccerguy3** [djpadbit/Sound-Physics#6]
I just pulled your latest commit from Feb 2 , compiled and tested , to find that there is no sound  if Liteloader is installed with  Sound-Physics . I have not tested exactly which commit breaks Liteloader compatibility yet . Easy to duplicate , just put Liteloader and S-P together and there will not be any sound in the game  

The last commit that does work with Liteloader and sound works is commit 12a2266c816cd4a1c9ddda8cd1e4ab3bc5b62004

This is a starting point to find what went wrong

**Comment by djpadbit** [comment]
It seems like even with commit https://github.com/djpadbit/Sound-Physics/commit/12a2266c816cd4a1c9ddda8cd1e4ab3bc5b62004 there isn't any sound, but it looks like Litleloader is messing with the sound system/handler and reloading it with its modifications after it had already been loaded once normally. I'll continue trying to figure out what's going on.

**Comment by djpadbit** [comment]
Nevermind i think i found the problem, It should be fixed in the next commit.

**Comment by djpadbit** [comment]
I'll close this issue as it should be fixed in https://github.com/djpadbit/Sound-Physics/commit/f6b30dc333ffbee9bf4003339f4bc6facdf655a7 but if it's not, feel free to reopen the issue.

**Comment by Tsoccerguy3** [comment]
Hi djpadbit , working great . Thank You . 

I just did a little update to mappings and Forge  , why not .

minecraft {
	version = "1.12.2-14.23.5.2810"
	runDir = "run"

	mappings = "stable_39"
}

wds@wds-GP72-6QF:~/dev/Sound-Physics$ ./gradlew build
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html.
This mapping 'stable_39' was designed for MC 1.12! Use at your own peril.
#################################################
         ForgeGradle 2.3-SNAPSHOT-3996470        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
                 Powered by MCP                  
             http://modcoderpack.com             
     by: Searge, ProfMobius, R4wk, ZeuX          
     Fesh0r, IngisKahn, bspkrs, LexManos         
#################################################
:deobfCompileDummyTask
:getVersionJson
:extractUserdev
Download https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2810/forge-1.12.2-14.23.5.2810.pom
Download https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2810/forge-1.12.2-14.23.5.2810-userdev.jar
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:applyBinaryPatches
:deobfProvidedDummyTask
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:deobfMcMCP
Applying SpecialSource...
Applying Exceptor...
:sourceApiJava
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava
:compileJava
:processResources
:classes
:jar
:sourceTestJava
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:reobfJar
:extractAnnotationsJar
:extractRangemapReplacedMain
/home/wds/dev/Sound-Physics/build/sources/main/java
:retromapReplacedMain
remapping source...
:sourceJar
:assemble
:check UP-TO-DATE
:build

BUILD SUCCESSFUL

Total time: 29.749 secs
