### ISSUE TITLE
Doesn't run in 1.12.2

### ISSUE THREAD

**Issue by Orangian** [djpadbit/Sound-Physics#63]
Hi. I installed this mod in a MultIMC instance with a few friends, and it isn't loading for any of us. It is in our mods folder, and we know that our mods are working since we have many modded blocks, but this mod doesn't even appear in the mod options menu. Is there anything we need to do other than dragging it into our mods folder?

**Comment by djpadbit** [comment]
What jar file did you put in your mods folder ?

**Comment by Orangian** [comment]
Sound-Physics-1.12.2-1.0.10-1.jar

**Comment by djpadbit** [comment]
The mod doesn't show up at all in the mods list ? Can i get the log ?

**Comment by Orangian** [comment]
Here is the log: https://pastebin.com/BksswK8Y
I searched the log and found this line which seems to be important: 
`8:56:28] [Client thread/INFO] [FML]: FML has found a non-mod file Sound-Physics-1.12.2-1.0.10-1.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.`

**Comment by djpadbit** [comment]
Could you check the md5 checksum of the file, it should be `622a2757551524a075bc0b236076a697`

**Comment by Orangian** [comment]
Huh, the hash ended up being 510FC04169F8B50D3D3FF330E0BDF31E. I'll redownload it and see if that fixes it.

**Comment by Orangian** [comment]
That fixed it. Thanks!
