### ISSUE TITLE
[1.12-bug] Incompatibility with Voice Chat Reloaded

### ISSUE THREAD

**Issue by gatoborrachon** [djpadbit/Sound-Physics#74]
**What is happening**
1.- When you use Sound Physics and [Voice Chat Reloaded](https://www.curseforge.com/minecraft/mc-mods/glibys-voice-chat-reloaded) you will clearly notice how you stop hearing that "echo" inside a cave when you mine or walk. 
(basically, Voice Chat Reloaded breaks Sound Physics' main feature, but at least i can still hear the muffed effect of rain)

**Versions**
Forge: 14.23.5.2854
Sound Physics: 1.12.2-1.0.10-1
Voice Chat Reloaded: [1.2.5](https://www.curseforge.com/minecraft/mc-mods/glibys-voice-chat-reloaded/files/3222659)

**Additional Notes**
While i was using the 1.7 backport, i noticed that amazing echo inside a cave, and then i remembered how it doesn't sounds like that in 1.12, and after trying the mod alone (in 1.12) i heard it again, so i looked for the guilty mod and my binary search resulted in Voice Chat Reloaded.

EDIT: I saw that the CurseForge page of Voice Chat Reloaded has this message:
> Support for the mod is complete, thanks to everyone who used this mod. 
> P.s. If you still need help with the mod (private improvements), you can always write to me in PM

so, if the only solution you can find requires me to edit that mod, just tell me what exactly i need to do and i will build it without problems, thanks for reading.

**Comment by gatoborrachon** [comment]
mmm, i don't see activity since the last year, was the project abandoned? or it was just relegated until you have more time? (i can wait, but i want to be sure, no problem if it was abandoned)

**Comment by djpadbit** [comment]
Yeah sorry, i'm currently not working that much on the project but i do plan on going back to it in the near futur.

**Comment by gatoborrachon** [comment]
oh ok, many thanks for answer, i was a bit worried but yeah. as i said, i will wait for the fix, no matter how much it takes

**Comment by MagmaSlime123** [comment]
Wait, was there a 1.7 backport? Where can I get it.

**Comment by djpadbit** [comment]
[Here](https://github.com/djpadbit/Sound-Physics/files/6964664/Sound-Physics-1.7.10.zip)'s a build from the latest commit of 1.7.10 backport. It's not at the same level of polish as the 1.12.2 version but it works.

**Comment by MagmaSlime123** [comment]
Well, looks cool, but I just tested, and it just acts as if its not even installed, no echo/reverb or anything.

Doubt you'll ever support 1.7.10, though it does still have a decent community that still uses that version.
It'd be nice if you did fix the mod up and made it work correctly tbh, but not gonna annoy you.

**Comment by djpadbit** [comment]
That's weird, last time i tested it, it worked. Does it show up in the mods list ?

**Comment by MagmaSlime123** [comment]
> That's weird, last time i tested it, it worked. Does it show up in the mods list ?

Yeah, it does. It just doesn't add any reverb/echos or anything.

**Comment by djpadbit** [comment]
Could you give the client logs ?

**Comment by MagmaSlime123** [comment]
Yeah, hang on.

EDIT: Alright. Tested again, same thing happened. Mod loads but doesn't do anything as if not installed.
[latest.log](https://github.com/djpadbit/Sound-Physics/files/6978051/latest.log)

I am making a modpack, and I basically did the whole mod removal/1 at a time thing WAY too much already. If I have to again, then I will, but its a pain in the ass to do tbh.

**Comment by MagmaSlime123** [comment]
> Could you give the client logs ?

Uh.. 15 days later. ^^

**Comment by djpadbit** [comment]
Sorry i've been busy with other stuff, i kinda forgot. But there doesn't seem to be anything wrong. I'm as confused as you. At this point you should make a seperate issue on github. Then try with the injector logging enabled in the config and send it again.

**Comment by gatoborrachon** [comment]
> you should make a seperate issue on github

yeah, i was about to say that but i forgot it too xd

**Comment by MagmaSlime123** [comment]
> Sorry i've been busy with other stuff, i kinda forgot. But there doesn't seem to be anything wrong. I'm as confused as you. At this point you should make a seperate issue on github. Then try with the injector logging enabled in the config and send it again.

Ah, alright.

**Comment by gatoborrachon** [comment]
well, after thinking about this a bit, in case that both mods (VoiceChatReloaded and SoundPhysics) were fundamentally incompatible, just tell me and i will get it, no problem

Source Code of VoiceChatReloaded: https://github.com/Icosider/GlibysVoiceChat

**Comment by djpadbit** [comment]
Ok i just realised this is stupid, i've been thinking why doesn't it work on your end but the compatibility is not in the newest release so that makes sense.
To sum it up, i added gliby's voice chat compatiblity because i wanted to play with it in a modpack and i commit it to the repo. Some time passes, and your issue pops up and having forgot that voice chat reloaded is gliby's voice chat reloaded it didn't click. So, it's already in the mod, but not in the latest release. [This](https://github.com/djpadbit/Sound-Physics/files/5758138/Sound-Physics-1.12.2-1.0.10-1.zip) release should be the latest one.
I'm extremely sorry but i really don't have time nowadays sadly so i didn't really look into your issue properly. You've been waiting for a while for something that was already done in November of 2020 ([here](https://github.com/djpadbit/Sound-Physics/commit/df7c7ab77c82f131cae260f3788c808213c4f31b) and [here](https://github.com/djpadbit/Sound-Physics/commit/f1648ae748405f61f95fa0a7cd7e1add7b2c6c7d) are the commits).
I haven't tested it on Voice Chat Reloaded 1.2.5 as there was only 1.2.4 at the time of writing the compatibility but it should work.

**Comment by gatoborrachon** [comment]
oh really no problem, i wanted to add the Voice Chat Reloaded mod (and as you say, aka Gliby's Voice Chat) to play with a friend and explain him some concepts, but at the end he (and me) don't had time to play due to school, so there is nothing to lament

also, if my previous message was a bit rude, sorry, i'm not a native english speaker.

And finally, i just wanted to comment this to avoid forgeting it with any answer by the dev, this happened with you in an old issue from this mod (totally my bad) and with Computronics, but again, there's really no problem, i should have added that VoiceChatReloaded had that name too, let me test the mod you gave me and i will close this issue, give me 1 week at most, if not tonight, many thanks for answer

**Comment by gatoborrachon** [comment]
yeah, it works pretty fine with Voice Chat Reloaded 1.2.5, i can hear my voice (using a weak laptop that i have) and i hear the echo and the muffed rain, so yeah, many thanks for all

**Comment by MagmaSlime123** [comment]
> yeah, it works pretty fine with Voice Chat Reloaded 1.2.5, i can hear my voice (using a weak laptop that i have) and i hear the echo and the muffed rain, so yeah, many thanks for all

Wait, does Sound Physics make your voice echo?!
If so then that's cool. Unnnless I'm being dumb and not reading that right.

**Comment by djpadbit** [comment]
Yes, i also added support for Voice Chat Reloaded sources so voices gets affected by Sound Physics, although a side effect is that the voices are less loud than without it.

**Comment by gatoborrachon** [comment]
> Wait, does Sound Physics make your voice echo?!

First, sorry, i wrote it wrong, i meant that i hear the echo that you get in mines when you walk, break or place a block, but by what we can se above, there's an actual compatibility feature in form of echos, and that's pretty sick, didn't noticed because i didn't knew about that

**Comment by MagmaSlime123** [comment]
> Yes, i also added support for Voice Chat Reloaded sources so voices gets affected by Sound Physics, although a side effect is that the voices are less loud than without it.

Ah, cool. Btw, please see #78. Pretty much a dupe of this issue but for 1.7.10. I do love this mod but am not a fan of Sound Filters due to how laggy it is if you want realistic reverb from it.

**Comment by guyk2210** [comment]
> **What is happening** 1.- When you use Sound Physics and [Voice Chat Reloaded](https://www.curseforge.com/minecraft/mc-mods/glibys-voice-chat-reloaded) you will clearly notice how you stop hearing that "echo" inside a cave when you mine or walk. (basically, Voice Chat Reloaded breaks Sound Physics' main feature, but at least i can still hear the muffed effect of rain)
> 
> **Versions** Forge: 14.23.5.2854 Sound Physics: 1.12.2-1.0.10-1 Voice Chat Reloaded: [1.2.5](https://www.curseforge.com/minecraft/mc-mods/glibys-voice-chat-reloaded/files/3222659)
> 
> **Additional Notes** While i was using the 1.7 backport, i noticed that amazing echo inside a cave, and then i remembered how it doesn't sounds like that in 1.12, and after trying the mod alone (in 1.12) i heard it again, so i looked for the guilty mod and my binary search resulted in Voice Chat Reloaded.
> 
> EDIT: I saw that the CurseForge page of Voice Chat Reloaded has this message:
> 
> > Support for the mod is complete, thanks to everyone who used this mod.
> > P.s. If you still need help with the mod (private improvements), you can always write to me in PM
> 
> so, if the only solution you can find requires me to edit that mod, just tell me what exactly i need to do and i will build it without problems, thanks for reading.

the way the voice chat works is by calculating the distance from the speaking player to send to all players in proximity at a volume the mod decides to send to the other players in that proximity, instead of 3D sound coming directly from the player, like all the other sounds (also, make sure it's mono audio(this is only what I think the problem is))

**Comment by gatoborrachon** [comment]
@guyk2210 oh, i will try with that option, thanks, but djpadbit has a version of SoundPhysics that fixes this issue already:
https://github.com/djpadbit/Sound-Physics/files/5758138/Sound-Physics-1.12.2-1.0.10-1.zip

**Comment by OvermindDL1** [comment]
Where is the source for the latest 1.7.10 code branch?  The 1.7.10-backport branch seems woefully out of date, considering the current 1.7.10 sound-physics jar being passed around is marked as version 1.1.1 and is using mixins, where the 1.7.10-backport branch does not, it's tagged 1.0.5 (1.0.6 in the mcmod.info file though for some reason) and no mixins, so it seems substantially different?

**Comment by OvermindDL1** [comment]
Think I found it, if anyone else needs it:  https://github.com/mist475/Sound-Physics
