### ISSUE TITLE
Any chances you could port this to 1.8.9

### ISSUE THREAD

**Issue by MRePotatoes** [djpadbit/Sound-Physics#9]
It'd be really nice to use on this older version, as I really do not enjoy the PVP system for < 1.8

**Comment by Nixel1324** [comment]
You're in luck MRePotatoes, combat is being improved massively in (one of) the next update(s): https://youtu.be/7-EPUhw2lFI

Now we just need the mod to update to current versions, although I'm sure that's easier said than done.

**Comment by djpadbit** [comment]
I'm sorry for the late reply but i'll maybe think about it, the main problem after porting it is maintain it. For example, i try to maintain the 1.7.10 backport but it's still a bit behind the 1.12.2 version because of the big changes in forge. I also made a port for 1.10.2 but never release it as it was for a friend. I did also port it to minecraft beta 1.7.3 for shits and giggles and to try and test how far i could port it. I could definitively make a port for 1.8.9 but i can't guarantee that it will be updated. I kind of rambled on but tl;dr maybe, but i probably won't update it.

**Comment by MRePotatoes** [comment]
@djpadbit it'd be cool and I personally don't mind it being not updated

**Comment by djpadbit** [comment]
I don't know if you still need the 1.8.9 version but i had nothing to do so i figured i might do it. So here it is [Sound-Physics-1.8.9.zip](https://github.com/djpadbit/Sound-Physics/files/3408884/Sound-Physics-1.8.9.zip), let me know if you find any kind bugs but it seems to be working fine. Like the 1.7.10 version, the GUI settings don't work though, if you want to change some settings you are going to have to edit the cfg file by hand.

**Comment by AndyistGD** [comment]
Hi! Is there any possibility this mod is going to be updated to 1.14.3?
Sad that this mod is as underrated as it is, hope it gets more known in the future.
Have a nice day.

**Comment by djpadbit** [comment]
As i said in issue https://github.com/djpadbit/Sound-Physics/issues/5, for now porting to newer version isn't really my main priority but in the future, probably.

**Comment by AndyistGD** [comment]
Ohh I understand. Thanks for your fast response and have a nice day!

**Comment by Blackrucat** [comment]
This is the fastest answer I ever had here in Github, thank you guys!

**Comment by Lifeisstrange74** [comment]
> I'm sorry for the late reply but i'll maybe think about it, the main problem after porting it is maintain it. For example, i try to maintain the 1.7.10 backport but it's still a bit behind the 1.12.2 version because of the big changes in forge. I also made a port for 1.10.2 but never release it as it was for a friend. I did also port it to minecraft beta 1.7.3 for shits and giggles and to try and test how far i could port it. I could definitively make a port for 1.8.9 but i can't guarantee that it will be updated. I kind of rambled on but tl;dr maybe, but i probably won't update it.

Do you still have the 1.10.2 port? I actually need it for some of my friends, we're on a 1.10.2 server

**Comment by djpadbit** [comment]
@Lifeisstrange74 I don't know if it still works and if it does it's probably very outdated but [here](https://github.com/djpadbit/Sound-Physics/files/6303223/Sound-Physics-1.10.2.jar.zip) it is.
