### ISSUE TITLE
Console/log spam OpenAL error AL_INVALID_VALUE

### ISSUE THREAD

**Issue by samve000** [djpadbit/Sound-Physics#91]
When I open a new world, the console starts spamming this:
![image](https://github.com/user-attachments/assets/ec0b36f9-1e30-41bf-812e-52bf8c22a600)

Full log file:
https://mclo.gs/udy2Pjc

**Comment by djpadbit** [comment]
I'm sorry but you posted the issue on the wrong GitHub repo, this one is only for Forge 1.12.2 (and not updated anymore lol).
The one you're looking for is [sound-physics-remastered](https://github.com/henkelmax/sound-physics-remastered) according to your version and jar file.

**Comment by samve000** [comment]
Oh sorry didn't realize thanks hahah
